### ISSUE TITLE
[BUG] When entry is valid, the admiralty input spacing gets smaller 

### ISSUE THREAD

**Issue by KatiePUX** [UKHO/admiralty-design-system#173]
**Describe the bug**
If you put a valid entry into the input field the admiralty input invalid spacing gets smaller. This is causing the page to bounce as the user completes a form.

**To Reproduce**
1. Go to 'UKHO data upload' > 'Send a new survey'
2. Click 'Name of survey' input field, enter 'K'
3. See error

**Expected behavior**
Spacing to not change and to be consistent with all input fields in the design system

**Screenshots**

1. 
![image](https://github.com/UKHO/admiralty-design-system/assets/106257212/08a97bc4-b261-4589-a360-e337fdb87d79)
2. 
![image](https://github.com/UKHO/admiralty-design-system/assets/106257212/f97e4781-ec39-4832-b0a1-17940c0a26d4)

**Comment by ecstaticrainbow** [comment]
Spoke to Katie and Luke, to resolve this issue we will remove the reserved space for the input error, this should bring everything closer together and also should fix the bouncing around issue. We are happy with the fact the page will stretch vertically when an error does exist but that is how GDS do it and other design systems. It is also worth checking that the CSS rules are setup correctly for the input error so that it doesn't drag the input around when it shows and doesnt show
